package drools.spring.rules;

import drools.spring.example.model.Symptom;
import drools.spring.example.model.Illness;
import drools.spring.example.model.User;
import java.util.List;
import java.util.ArrayList;

global ArrayList<Illness> illnesses;
global ArrayList<Illness> allSymptomIllnesses;

rule "All illnesses - Fever"
	agenda-group "all-illnesses"
    when
        $list: List() from collect(Symptom( ))
       
        $resList: List(size > 0) from accumulate(
            $sym: Symptom(
                term == Symptom.Term.SNEEZE || term == Symptom.Term.SORE_THROAT || term == Symptom.Term.COUGH
                || term == Symptom.Term.TEMP_OVER_38 || term == Symptom.Term.RUNNY_NOSE || term == Symptom.Term.HEADACHE
                || term == Symptom.Term.SHIVER
            ) from $list,
            init(List<Symptom> list1 = new ArrayList<Symptom>();),
            action(list1.add($sym);),
            result(list1)
        )
    then    	
        Illness i = new Illness();
	   	i.setCategory(Illness.Category.FIRST);
	   	i.setName("Fever");
	   	i.setSymptoms($resList);
	   	illnesses.add(i);
end

rule "One illness - Fever"
	agenda-group "one-illness"
    when
        $list: List() from collect(Symptom( ))
       
        $resList: List(size >= 4) from accumulate(
            $sym: Symptom(
                term == Symptom.Term.SNEEZE || term == Symptom.Term.SORE_THROAT || term == Symptom.Term.COUGH
                || term == Symptom.Term.TEMP_OVER_38 || term == Symptom.Term.RUNNY_NOSE || term == Symptom.Term.HEADACHE
                || term == Symptom.Term.SHIVER
            ) from $list,
            init(List<Symptom> list1 = new ArrayList<Symptom>();),
            action(list1.add($sym);),
            result(list1)
        )
    then 
    	Illness illness = new Illness();
	    illness.setCategory(Illness.Category.FIRST);
	   	illness.setName("Fever"); 
	    illness.setSymptoms($resList);
    	if ($resList.size() == 7){
	    	System.out.println("ovdje je nova bolest sa svim simptomima: "+ illness.getName());
	    	allSymptomIllnesses.add(illness);
        } else{
		   	System.out.println("ovdje je nova bolest: "+ i.getName());
	    	illnesses.add(illness);
        }  	
        
end

rule "FEVER - Symptoms"
	no-loop 
	agenda-group "symptoms"
    when
        $i: Illness( name == "Fever" )
    then
    	Symptom s = new Symptom();
    	s.setTerm(Symptom.Term.RUNNY_NOSE);
    	s.setSpecific(false);
    	s.setHelper("Runny nose");
    	$i.getSymptoms().add(s);
    	Symptom s1 = new Symptom();
    	s1.setTerm(Symptom.Term.SORE_THROAT);
    	s1.setSpecific(false);
    	s1.setHelper("Sore throat");
    	$i.getSymptoms().add(s1);
    	Symptom s2 = new Symptom();
        s2.setTerm(Symptom.Term.HEADACHE);
    	s2.setSpecific(false);
    	s2.setHelper("Headache");
    	$i.getSymptoms().add(s2);
    	Symptom s3 = new Symptom();
    	s3.setTerm(Symptom.Term.SNEEZE);
    	s3.setSpecific(false);
    	s3.setHelper("Sneeze");
    	$i.getSymptoms().add(s3);
    	Symptom s4 = new Symptom();
    	s4.setTerm(Symptom.Term.COUGH);
    	s4.setSpecific(false);
    	s4.setHelper("Cough");
    	$i.getSymptoms().add(s4);
    	Symptom s5 = new Symptom();
    	s5.setTerm(Symptom.Term.TEMP_OVER_38);
    	s5.setSpecific(false);
    	s5.setHelper("Temperature over 38");
    	$i.getSymptoms().add(s5);
    	Symptom s6 = new Symptom();
    	s6.setTerm(Symptom.Term.SHIVER);
    	s6.setSpecific(false);
    	s6.setHelper("Shiver");
    	$i.getSymptoms().add(s6);
    	update($i);
    	
end


