package drools.spring.rules;

import drools.spring.example.model.Symptom;
import drools.spring.example.model.Illness;
import drools.spring.example.model.Diagnose;
import java.util.ArrayList;
import java.util.Date;

global Long pId;



rule "Patient sufferes from hypertension more than 6 months"
	salience 50
	agenda-group "set-symptom-num"
	no-loop
	lock-on-active true
    when
    	 $illness: Illness( name == "Chronic Kidney Disease" && $numOfSymptoms : symptomsFound &&
    	  	$numOfSpecSymptoms: specificSymptomsFound && $sym : symptomTermsFound)
    	 
    	 $s: Symptom(Symptom.Term.SUFFERES_FROM_HYPERTENSION_FOR_AT_LEAST_6_MONTHS not memberOf $sym)
    	 
    	 $d: Diagnose( $date: date && illnessName == "Hypertension" &&  patientId == pId &&  $date > (addMonths(6))  )
    	
    then
    	$illness.setSymptomsFound($numOfSymptoms + 1);
    	$illness.setSpecificSymptomsFound($numOfSpecSymptoms + 1);
    	$illness.getSymptomTermsFound().add(Symptom.Term.SUFFERES_FROM_HYPERTENSION_FOR_AT_LEAST_6_MONTHS);
    	update($illness);
    	
end


rule "Patient sufferes from Diabetes"
	salience 50
	agenda-group "set-symptom-num"
	no-loop
	lock-on-active true
    when
    	
    	$d: Diagnose( illnessName == "Diabetes" && patientId == pId )
    	$illness: Illness( name == "Chronic Kidney Disease" && $numOfSymptoms : symptomsFound &&
    	  	$numOfSpecSymptoms: specificSymptomsFound && $sym : symptomTermsFound)
    	  	
    	$s: Symptom(Symptom.Term.SUFFERES_FROM_DIABETES not memberOf $sym)
    	
    then
    	$illness.setSymptomsFound($numOfSymptoms + 1);
    	$illness.setSpecificSymptomsFound($numOfSpecSymptoms + 1);
    	$illness.getSymptomTermsFound().add(Symptom.Term.SUFFERES_FROM_DIABETES);
    	update($illness);
    	
end

rule "Chronic Kidney Disease - Symptoms"
	no-loop 
	agenda-group "symptoms"
    when
        $i: Illness( name == "Chronic Kidney Disease" )
    then
    	Symptom s = new Symptom();
    	s.setTerm(Symptom.Term.CHEST_PAIN);
    	s.setSpecific(false);
    	s.setHelper("Chest pain");
    	$i.getSymptoms().add(s);
    	Symptom s1 = new Symptom();
    	s1.setTerm(Symptom.Term.LEGS_AND_JOINTS_SWELLING);
    	s1.setSpecific(false);
    	s1.setHelper("Legs and joints swelling");
    	$i.getSymptoms().add(s1);
    	Symptom s2 = new Symptom();
        s2.setTerm(Symptom.Term.FATIGUE);
    	s2.setSpecific(false);
    	s2.setHelper("Fatigue");
    	$i.getSymptoms().add(s2);
    	Symptom s3 = new Symptom();
    	s3.setTerm(Symptom.Term.NOCTURIA);
    	s3.setSpecific(false);
    	s3.setHelper("Nocturia");
    	$i.getSymptoms().add(s3);
    	Symptom s4 = new Symptom();
    	s4.setTerm(Symptom.Term.CHOKING);
    	s4.setSpecific(false);
    	s4.setHelper("Choking");
    	$i.getSymptoms().add(s4);
    	Symptom s5 = new Symptom();
    	s5.setTerm(Symptom.Term.SUFFERES_FROM_HYPERTENSION_FOR_AT_LEAST_6_MONTHS);
    	s5.setSpecific(true);
    	s5.setHelper("Sufferes from Hypertension for at least 6 months");
    	$i.getSymptoms().add(s5);
    	Symptom s6 = new Symptom();
    	s6.setTerm(Symptom.Term.SUFFERES_FROM_DIABETES);
    	s6.setSpecific(true);
    	s6.setHelper("Sufferes from diabetes");
    	$i.getSymptoms().add(s6);
    	update($i);
    	
end
