package drools.spring.rules;

import drools.spring.example.model.Record;
import drools.spring.example.model.Medicament;
import drools.spring.example.model.MedicamentAllergy;
import drools.spring.example.model.Ingridient;
import drools.spring.example.model.IngridientAllergy;
import drools.spring.example.model.Illness;
import drools.spring.example.model.User;
import drools.spring.example.model.Patient;
import java.util.List;
import java.util.ArrayList;

global Long idPatient;

rule "Check if patient is allergic to medicament"
	agenda-group "check-allergies"
    when
        $medicament: Medicament( $medName: name )
    	$allergy: MedicamentAllergy( patientId == idPatient && medicamentName == $medName )
    then    	
    	insert($medName);
end

rule "Check if patient is allergic to ingridient"
	agenda-group "check-allergies"
    when
        $ingridient: Ingridient( $ingrName: name )
    	$allergy: IngridientAllergy( patientId == idPatient && ingridientName == $ingrName )
    then   
    	insert($ingrName);
end


